export const symbols = [
    { value: "AAL", label: "AAL", name: "American Airlines Group" },
    { value: "AAPL", label: "AAPL", name: "Apple"},
    { value: "ABNB", label: "ABNB", name: "Airbnb" },
    { value: "ACHR", label: "ACHR", name: "Archer Aviation" },
    { value: "ADBE", label: "ADBE", name: "Adobe" },
    { value: "AFRM", label: "AFRM", name: "Affirm Holdings" },
    { value: "AI", label: "AI", name: "C3.ai" },
    { value: "ALAB", label: "ALAB", name: "Astria Therapeutics" },
    { value: "AMC", label: "AMC", name: "AMC Entertainment Holdings" },
    { value: "AMD", label: "AMD", name: "Advanced Micro Devices" },
    { value: "AMAT", label: "AMAT", name: "Applied Materials" },
    { value: "AMZN", label: "AMZN", name: "Amazon"},
    { value: "ANET", label: "ANET", name: "Arista Networks" },
    { value: "APP", label: "APP", name: "AppLovin" },
    { value: "APLD", label: "APLD", name: "Applied Digital" },
    { value: "APPS", label: "APPS", name: "Digital Turbine" },
    { value: "ARM", label: "ARM", name: "ARM Holdings" },
    { value: "ASML", label: "ASML", name: "ASML Holding" },
    { value: "ASTS", label: "ASTS", name: "AST SpaceMobile" },
    { value: "AVGO", label: "AVGO", name: "Broadcom" },
    { value: "BA", label: "BA", name: "Boeing" },
    { value: "BABA", label: "BABA", name: "Alibaba Group" },
    { value: "BAC", label: "BAC", name: "Bank of America" },
    { value: "BB", label: "BB", name: "BlackBerry" },
    { value: "BBAI", label: "BBAI", name: "BigBear.ai Holdings" },
    { value: "BEKE", label: "BEKE", name: "KE Holdings" },
    { value: "BIDU", label: "BIDU", name: "Baidu" },
    { value: "BILI", label: "BILI", name: "Bilibili" },
    { value: "BMY", label: "BMY", name: "Bristol-Myers Squibb" },
    { value: "BP", label: "BP", name: "BP p.l.c." },
    { value: "C", label: "C", name: "Citigroup" },
    { value: "CCL", label: "CCL", name: "Carnival Corporation" },
    { value: "CELH", label: "CELH", name: "Celsius Holdings" },
    { value: "CFLT", label: "CFLT", name: "Confluent" },
    { value: "CLF", label: "CLF", name: "Cleveland-Cliffs" },
    { value: "CLMT", label: "CLMT", name: "Calumet Specialty Products Partners" },
    { value: "CMCSA", label: "CMCSA", name: "Comcast" },
    { value: "CMG", label: "CMG", name: "Chipotle Mexican Grill" },
    { value: "COF", label: "COF", name: "Capital One Financial" },
    { value: "COIN", label: "COIN", name: "Coinbase" },
    { value: "COST", label: "COST", name: "Costco Wholesale" },
    { value: "CRM", label: "CRM", name: "Salesforce" },
    { value: "CRWD", label: "CRWD", name: "CrowdStrike Holdings" },
    { value: "CSCO", label: "CSCO", name: "Cisco Systems" },
    { value: "CVNA", label: "CVNA", name: "Carvana" },
    { value: "CVS", label: "CVS", name: "CVS Health" },
    { value: "CVX", label: "CVX", name: "Chevron" },
    { value: "DAL", label: "DAL", name: "Delta Air Lines" },
    { value: "DASH", label: "DASH", name: "DoorDash" },
    { value: "DDOG", label: "DDOG", name: "Datadog" },
    { value: "DECK", label: "DECK", name: "Deckers Outdoor" },
    { value: "DELL", label: "DELL", name: "Dell Technologies" },
    { value: "DIS", label: "DIS", name: "Walt Disney" },
    { value: "DJT", label: "DJT", name: "Trump Media & Technology Group" },
    { value: "DKNG", label: "DKNG", name: "DraftKings" },
    { value: "ELF", label: "ELF", name: "e.l.f. Beauty" },
    { value: "ENPH", label: "ENPH", name: "Enphase Energy" },
    { value: "ENVX", label: "ENVX", name: "Enovix Corporation" },
    { value: "ET", label: "ET", name: "Energy Transfer" },
    { value: "F", label: "F", name: "Ford Motor" },
    { value: "FCX", label: "FCX", name: "Freeport-McMoRan" },
    { value: "FSLR", label: "FSLR", name: "First Solar" },
    { value: "FSLY", label: "FSLY", name: "Fastly" },
    { value: "FUBO", label: "FUBO", name: "fuboTV" },
    { value: "FUTU", label: "FUTU", name: "Futu Holdings" },
    { value: "GE", label: "GE", name: "General Electric" },
    { value: "GILD", label: "GILD", name: "Gilead Sciences" },
    { value: "GM", label: "GM", name: "General Motors" },
    { value: "GME", label: "GME", name: "GameStop" },
    { value: "GOOG", label: "GOOG", name: "Alphabet Class C" },
    { value: "GOOGL", label: "GOOGL", name: "Alphabet Class A" },
    { value: "GOLD", label: "GOLD", name: "Barrick Gold" },
    { value: "GRAB", label: "GRAB", name: "Grab Holdings" },
    { value: "GS", label: "GS", name: "Goldman Sachs Group" },
    { value: "GT", label: "GT", name: "Goodyear Tire & Rubber" },
    { value: "HIMS", label: "HIMS", name: "Hims & Hers Health" },
    { value: "HIMX", label: "HIMX", name: "Himax Technologies" },
    { value: "HOOD", label: "HOOD", name: "Robinhood Markets" },
    { value: "IBIT", label: "IBIT", name: "iShares Bitcoin Trust" },
    { value: "IBM", label: "IBM", name: "International Business Machines" },
    { value: "INTC", label: "INTC", name: "Intel" },
    { value: "IONQ", label: "IONQ", name: "IonQ" },
    { value: "IQ", label: "IQ", name: "iQIYI" },
    { value: "IRBT", label: "IRBT", name: "iRobot" },
    { value: "IREN", label: "IREN", name: "Iris Energy" },
    { value: "JD", label: "JD", name: "JD.com" },
    { value: "JNJ", label: "JNJ", name: "Johnson & Johnson" },
    { value: "JPM", label: "JPM", name: "JPMorgan Chase & Co." },
    { value: "KO", label: "KO", name: "Coca-Cola" },
    { value: "LCID", label: "LCID", name: "Lucid Group" },
    { value: "LLY", label: "LLY", name: "Eli Lilly and Company" },
    { value: "LRCX", label: "LRCX", name: "Lam Research" },
    { value: "LUNR", label: "LUNR", name: "Intuitive Machines" },
    { value: "LUV", label: "LUV", name: "Southwest Airlines" },
    { value: "LYFT", label: "LYFT", name: "Lyft" },
    { value: "MARA", label: "MARA", name: "Marathon Digital Holdings" },
    { value: "MBLY", label: "MBLY", name: "Mobileye Global" },
    { value: "MCD", label: "MCD", name: "McDonald's" },
    { value: "META", label: "META", name: "Meta Platforms" },
    { value: "MGM", label: "MGM", name: "MGM Resorts International" },
    { value: "MMM", label: "MMM", name: "3M Company" },
    { value: "MRK", label: "MRK", name: "Merck & Co." },
    { value: "MRNA", label: "MRNA", name: "Moderna" },
    { value: "MRVL", label: "MRVL", name: "Marvell Technology" },
    { value: "MSFT", label: "MSFT", name: "Microsoft" },
    { value: "MSTR", label: "MSTR", name: "MicroStrategy" },
    { value: "MSTU", label: "MSTU", name: "Microstrategy (New)" },
    { value: "MSTX", label: "MSTX", name: "Mast Therapeutics" },
    { value: "MU", label: "MU", name: "Micron Technology" },
    { value: "NEE", label: "NEE", name: "NextEra Energy" },
    { value: "NEM", label: "NEM", name: "Newmont" },
    { value: "NFLX", label: "NFLX", name: "Netflix" },
    { value: "NIO", label: "NIO", name: "NIO Inc." },
    { value: "NKE", label: "NKE", name: "Nike" },
    { value: "NKLA", label: "NKLA", name: "Nikola" },
    { value: "NOK", label: "NOK", name: "Nokia" },
    { value: "NOW", label: "NOW", name: "ServiceNow" },
    { value: "NVDA", label: "NVDA", name: "NVIDIA" },
    { value: "NVDL", label: "NVDL", name: "NVIDIA (New)" },
    { value: "NVO", label: "NVO", name: "Novo Nordisk" },
    { value: "NVT", label: "NVT", name: "nVent Electric" },
    { value: "NXE", label: "NXE", name: "NexGen Energy" },
    { value: "OKLO", label: "OKLO", name: "Oklo" },
    { value: "ONON", label: "ONON", name: "On Holding" },
    { value: "ORCL", label: "ORCL", name: "Oracle" },
    { value: "OXY", label: "OXY", name: "Occidental Petroleum" },
    { value: "PAA", label: "PAA", name: "Plains All American Pipeline" },
    { value: "PANW", label: "PANW", name: "Palo Alto Networks" },
    { value: "PBI", label: "PBI", name: "Pitney Bowes" },
    { value: "PDD", label: "PDD", name: "PDD Holdings" },
    { value: "PFE", label: "PFE", name: "Pfizer" },
    { value: "PG", label: "PG", name: "Procter & Gamble" },
    { value: "PINS", label: "PINS", name: "Pinterest" },
    { value: "PLTR", label: "PLTR", name: "Palantir Technologies" },
    { value: "PLUG", label: "PLUG", name: "Plug Power" },
    { value: "PTON", label: "PTON", name: "Peloton Interactive" },
    { value: "PYPL", label: "PYPL", name: "PayPal Holdings" },
    { value: "QBTS", label: "QBTS", name: "D-Wave Quantum" },
    { value: "QCOM", label: "QCOM", name: "Qualcomm" },
    { value: "QQQ", label: "QQQ", name: "Invesco QQQ Trust" },
    { value: "QS", label: "QS", name: "QuantumScape" },
    { value: "QUBT", label: "QUBT", name: "Quantum Computing" },
    { value: "RBLX", label: "RBLX", name: "Roblox" },
    { value: "RDDT", label: "RDDT", name: "Reddit" },
    { value: "RDFN", label: "RDFN", name: "Redfin" },
    { value: "RGTI", label: "RGTI", name: "Rigetti Computing" },
    { value: "RIOT", label: "RIOT", name: "Riot Platforms" },
    { value: "RIVN", label: "RIVN", name: "Rivian Automotive" },
    { value: "RKLB", label: "RKLB", name: "Rocket Lab USA" },
    { value: "ROKU", label: "ROKU", name: "Roku" },
    { value: "RXRX", label: "RXRX", name: "Recursion Pharmaceuticals" },
    { value: "SAVE", label: "SAVE", name: "Spirit Airlines" },
    { value: "SBLK", label: "SBLK", name: "Star Bulk Carriers" },
    { value: "SBUX", label: "SBUX", name: "Starbucks" },
    { value: "SCHW", label: "SCHW", name: "Charles Schwab" },
    { value: "SEDG", label: "SEDG", name: "SolarEdge Technologies" },
    { value: "SERV", label: "SERV", name: "ServiceMaster Global Holdings" },
    { value: "SHOP", label: "SHOP", name: "Shopify" },
    { value: "SMCI", label: "SMCI", name: "Super Micro Computer" },
    { value: "SNAP", label: "SNAP", name: "Snap" },
    { value: "SNOW", label: "SNOW", name: "Snowflake" },
    { value: "SOFI", label: "SOFI", name: "SoFi Technologies" },
    { value: "SOUN", label: "SOUN", name: "SoundHound AI" },
    { value: "SPOT", label: "SPOT", name: "Spotify Technology" },
    { value: "SPX", label: "SPX", name: "S&P 500 Index" },
    { value: "SPY", label: "SPY", name: "SPDR S&P 500 ETF Trust" },
    { value: "SQ", label: "SQ", name: "Block" },
    { value: "T", label: "T", name: "AT&T" },
    { value: "TDOC", label: "TDOC", name: "Teladoc Health" },
    { value: "TECK", label: "TECK", name: "Teck Resources" },
    { value: "TEM", label: "TEM", name: "Tempus AI" },
    { value: "TGT", label: "TGT", name: "Target" },
    { value: "TIGR", label: "TIGR", name: "UP Fintech Holding" },
    { value: "TLRY", label: "TLRY", name: "Tilray Brands" },
    { value: "TTD", label: "TTD", name: "The Trade Desk" },
    { value: "TSLA", label: "TSLA", name: "Tesla"},
    { value: "U", label: "U", name: "Unity Software" },
    { value: "UBER", label: "UBER", name: "Uber Technologies" },
    { value: "UPS", label: "UPS", name: "United Parcel Service" },
    { value: "UPST", label: "UPST", name: "Upstart Holdings" },
    { value: "VALE", label: "VALE", name: "Vale S.A." },
    { value: "VRT", label: "VRT", name: "Vertiv Holdings" },
    { value: "VST", label: "VST", name: "Vistra" },
    { value: "VZ", label: "VZ", name: "Verizon Communications" },
    { value: "WBA", label: "WBA", name: "Walgreens Boots Alliance" },
    { value: "WBD", label: "WBD", name: "Warner Bros. Discovery" },
    { value: "WDC", label: "WDC", name: "Western Digital" },
    { value: "WFC", label: "WFC", name: "Wells Fargo & Company" },
    { value: "WMT", label: "WMT", name: "Walmart" },
    { value: "WULF", label: "WULF", name: "TeraWulf" },
    { value: "XOM", label: "XOM", name: "Exxon Mobil" },
    { value: "XYZ", label: "XYZ", name: "XYZ Corporation" },
    { value: "ZIM", label: "ZIM", name: "ZIM Integrated Shipping Services" }
]